Repository adobecom/dc, pull requests merged in 2023-08, with the labels that each got.

#318 DCXY-18730 use min-height for fsw
  acrobat/styles/styles.css
Labels: trivial

#324 MWPW-135188 JP CSP Update
  acrobat/scripts/contentSecurityPolicy/prod.js
  acrobat/scripts/contentSecurityPolicy/stage.js
Labels: trivial

#289 CSP Update
  acrobat/scripts/contentSecurityPolicy/dev.js
  acrobat/scripts/contentSecurityPolicy/prod.js
  acrobat/scripts/contentSecurityPolicy/stage.js
Labels: trivial

#319 0.2333
  acrobat/blocks/dc-converter-widget-ootb/dc-converter-widget-ootb.js
  acrobat/blocks/dc-converter-widget/dc-converter-widget.js
  acrobat/scripts/contentSecurityPolicy/prod.js
  acrobat/scripts/contentSecurityPolicy/stage.js
  acrobat/scripts/maps/localeMap.js
  acrobat/scripts/scripts.js
  test/blocks/dc-converter-widget-ootb/dc-converter-widget-ootb.jest.js
  test/blocks/dc-converter-widget-ootb/dc-converter-widget-ootb.test.js
  test/blocks/dc-converter-widget-ootb/mocks/body.html
  test/blocks/dc-converter-widget-ootb/mocks/body_cache.html
  test/blocks/dc-converter-widget-ootb/mocks/head.html
  test/blocks/dc-converter-widget-ootb/mocks/widget.html
  test/blocks/eventwrapper/eventwrapper.test.js
  test/blocks/pricing-card/mocks/body_noinitialoption.html
  test/blocks/pricing-card/pricing-card.test.js
Labels: verified

#336 fix proxy fetch url in unit test
  test/blocks/dc-converter-widget/dc-converter-widget.jest.js
Labels: trivial

#338 fixing unit test
  acrobat/scripts/dcLana.js
Labels: trivial

#342 MWPW-135361 Gen Cache Update
  acrobat/blocks/dc-converter-widget/dc-converter-widget.js
Labels: trivial

#343 MWPW-135361 Gen Cache Update
  acrobat/blocks/dc-converter-widget/dc-converter-widget.js
Labels: trivial

#351 MWPW-135361
  acrobat/blocks/dc-converter-widget/dc-converter-widget.js
  acrobat/scripts/scripts.js
  test/scripts/scripts.jest.js
Labels: @frictionless
