Repository adobecom/dc, pull requests merged in 2023-04, with the labels that each got.

#199 Improving LCP first load time.
  acrobat/scripts/scripts.js
Labels: trivial

#201 MWPW-129368
  acrobat/blocks/dc-converter-widget/dc-converter-widget.js
  acrobat/scripts/dcLana.js
  acrobat/scripts/scripts.js
  test/scripts/dcLana.test.js
Labels: run-nala

#203 MWPW-129282
  acrobat/blocks/eventwrapper/eventwrapper.js
Labels: run-nala, @frictionless, trivial

#215 DCXY-16330 remove overflow: hidden
  acrobat/styles/styles.css
Labels: trivial

#223 MWPW-129578
  acrobat/scripts/contentSecurityPolicy/csp.js
  acrobat/scripts/contentSecurityPolicy/dev.js
  acrobat/scripts/contentSecurityPolicy/prod.js
  acrobat/scripts/contentSecurityPolicy/stage.js
Labels: trivial

#221 Sitemap expansion
  helix-query.yaml
  helix-sitemap.yaml
Labels: trivial

#225 0.2317
  acrobat/scripts/alloy/browserExt.js
  acrobat/scripts/contentSecurityPolicy/dev.js
  acrobat/scripts/contentSecurityPolicy/stage.js
  acrobat/scripts/frictionless.js
  acrobat/scripts/maps/localeMap.js
  acrobat/scripts/maps/verbRedirMap.js
  acrobat/scripts/scripts.js
  helix-sitemap.yaml
Labels: run-nala, @frictionless, verified
