Repository adobecom/dc, pull requests merged in 2025-05, with the labels that each got.

#1155 MWPW-172124x: Consider the border size on the max width of the dropzone
  acrobat/blocks/verb-widget/verb-widget.css
Labels: trivial

#1167 MWPW-173154 (Covert PDF) Support for .form, .indd, .ai and .psd
  acrobat/blocks/verb-widget/verb-widget.js
Labels: trivial

#1166 [MWPW-173298] Browser tab closure events overlap with other terminal events
  acrobat/blocks/verb-widget/verb-widget.js
Labels: bug

#1189 MWPW-173691
  acrobat/blocks/verb-widget/verb-widget.js
Labels: trivial

#1185 MWPW-171607 Add batch 2a E2E test cases
  test/e2e/features/unity/regression/L2a-verbs.feature
  test/e2e/features/unity/smoke/verbs.feature
  test/e2e/page-objects/pngtopdf.page.js
  test/e2e/page-objects/unity.page.js
  test/e2e/step-definitions/dc.steps.js
  test/e2e/test-files/test.png
Labels: test
